import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "oxc",
    "react",
    "jsx-a11y",
    "nextjs",
  ],
  env: {
    builtin: true,
  },
  ignorePatterns: [
    "**/node_modules/**",
    "**/dist/**",
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/.vercel/**",
    "**/coverage/**",
    "**/pnpm-lock.yaml",
    "**/*.min.js",
  ],
  rules: {
    "typescript/no-explicit-any": ["error", { fixToUnknown: true }],
    "react/react-in-jsx-scope": "off",
    "jsx-a11y/no-autofocus": "off",
    /**
     * Every `<img>` in this codebase points at a `blob:` or `data:` URL built
     * in the browser from a file the user just picked. `next/image` cannot
     * optimise those — there is no origin to fetch from and no build-time size
     * to reason about — so the rule has nothing to offer here.
     */
    "nextjs/no-img-element": "off",
  },
  overrides: [
    {
      /**
       * Generated by the shadcn CLI and overwritten whenever a component is
       * re-added, so local a11y edits do not survive. Upstream's markup is the
       * thing to fix, not our copy of it.
       */
      files: ["components/ui/**"],
      rules: {
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/no-noninteractive-element-interactions": "off",
        "jsx-a11y/no-static-element-interactions": "off",
        "jsx-a11y/prefer-tag-over-role": "off",
      },
    },
  ],
});
